# Sevalla Configuration File
# This file configures the build and deployment settings for Sevalla

name: wedding-website
type: static

build:
  command: npm install && npm run build
  output: out
  node_version: 20

# Static site configuration
static:
  # Serve all files from the out directory
  directory: out

# Routes configuration
routes:
  - from: /*
    to: /index.html
    status: 200

# Headers for security
headers:
  - path: /*
    headers:
      - key: X-Content-Type-Options
        value: nosniff
      - key: X-Frame-Options
        value: DENY
      - key: X-XSS-Protection
        value: 1; mode=block

